apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 3
            periodSeconds: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 15s }
        - analysis:
            templates:
              - templateName: health-check
        - setWeight: 50
        - pause: { duration: 15s }
        - setWeight: 100
